# vim: ft=yaml.ansible
---
aap_organizations:
  - name: RamenDR TechDemo
    galaxy_credentials: Ansible Galaxy

controller_settings:
  - name: AWX_COLLECTIONS_ENABLED
    value: true

  - name: AWX_ROLES_ENABLED
    value: true

controller_projects: []
#  - name: Demo Project
#    state: absent

#  - name: RamenDR TechDemo GitOps
#    organization: RamenDR TechDemo
#    scm_branch: main
#    scm_clean: "no"
#    scm_delete_on_update: "no"
#    scm_type: git
#    scm_update_on_launch: "yes"
#    scm_url: https://github.com/validatedpatterns-demos/rhvp.federated_edge_observability.git
#    wait: true
#    update_project: true

controller_schedules: []

controller_inventories: []

controller_inventory_sources: []

controller_credential_types:
  - name: RHSMcredential
    description: RHSM Credentials
    kind: cloud
    inputs:
      fields:
        - id: username
          type: string
          label: RHSM User name
          secret: true
        - id: password
          type: string
          label: RHSM password
          secret: true
      required:
        - username
        - password
    injectors:
      extra_vars:
        rhsm_username: "{  { username }}"
        rhsm_password: "{  { password }}"

controller_templates:
  - name: Demo Job Template
    state: absent

controller_credential_input_sources:
  - source_credential: Hashivault
    target_credential: vm-private-key
    input_field_name: username
    metadata:
      secret_backend: secret
      secret_path: hub/vm-ssh
      secret_key: username

  - source_credential: Hashivault
    target_credential: vm-private-key
    input_field_name: ssh_key_data
    metadata:
      secret_backend: secret
      secret_path: hub/vm-ssh
      secret_key: privatekey

  - source_credential: Hashivault
    target_credential: rhsm_credential
    input_field_name: username
    metadata:
      secret_backend: secret
      secret_path: hub/rhsm
      secret_key: username

  - source_credential: Hashivault
    target_credential: rhsm_credential
    input_field_name: password
    metadata:
      secret_backend: secret
      secret_path: hub/rhsm
      secret_key: password

controller_credentials:
  - name: Hashivault
    description: In-Cluster Hashicorp vault lookup
    organization: Federated Edge Observability
    credential_type: HashiCorp Vault Secret Lookup
    inputs:
      url: "{{ secrets['vault_url'] }}"
      token: "{{ secrets['vault_root_token'] }}"
      cacert: "{{ secrets['vault_ca'] }}"
      api_version: v2

  - name: rhsm_credential
    description: RHSM credential registering RHEL VMs
    organization: Federated Edge Observability
    credential_type: RHSMcredential

  - name: vm-private-key
    description: Machine credential for virtual machines
    organization: Federated Edge Observability
    credential_type: Machine
